name: Node.js CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/mike/apps/order-service
          git pull origin main
          git status
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo PORT=3001 >> .env
          npm ci
          npm run build
          pm2 restart order-service